# Generated by Django 5.2.3 on 2025-06-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catfact',
            old_name='decription',
            new_name='description',
        ),
    ]
